03 lection1
js-tasks-ru/htmlcss-20210610_alexandrkonuhov pull request #3
Opened 2021-06-19 13:28 UTC by akonuhov

2021-06-28 21:13 UTC, GSemikozov requested changes

2021-06-28 21:13 UTC, GSemikozov commented on components/page/page.css
> +    width: 1440px;
все-таки 1110px

2021-06-28 21:13 UTC, GSemikozov commented on components/header/header.css
> +    padding-left: 100px;
если обернуть содержимое в .page__box - тогда этот паддинг не нужен будет

2021-06-28 21:13 UTC, GSemikozov commented on components/footer/footer.css
> +    margin-left: 417px;
если обернуть содержимое в .page__box - тогда этот марджин не нужен будет

2021-06-28 21:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary::-webkit-details-marker {
селекторы тегов в БЭМ не рекомендуется использовать, поэтому - .accordion__summary

2021-06-28 21:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 50%;
не стоит так ограничивать ширину - на мобилке будет очень маленьким)

2021-06-28 21:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +svg {
нужно задать класс по БЭМ

2021-06-28 21:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary .marker{
вместо summary .marker - .accordion__marker

2021-06-28 21:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .marker{
details[open] -> .accordion[open]

2021-07-01 08:52 UTC, akonuhov commented on components/page/page.css
> +    width: 1440px;
Исправил

2021-07-01 08:53 UTC, akonuhov commented on components/header/header.css
> +    padding-left: 100px;
Исправил

2021-07-01 08:53 UTC, akonuhov commented on components/footer/footer.css
> +    margin-left: 417px;
Исправил

2021-07-01 08:53 UTC, akonuhov commented on 03-lection1/02-accordion/accordion.css
> +summary::-webkit-details-marker {
Готово

2021-07-01 08:54 UTC, akonuhov commented on 03-lection1/02-accordion/accordion.css
> +    width: 50%;
Поправил

2021-07-01 08:54 UTC, akonuhov commented on 03-lection1/02-accordion/accordion.css
> +svg {
Задал

2021-07-01 08:54 UTC, akonuhov commented on 03-lection1/02-accordion/accordion.css
> +summary .marker{
Исправил

2021-07-01 08:55 UTC, akonuhov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .marker{
Исправил

2021-07-01 20:57 UTC, GSemikozov requested changes

2021-07-01 20:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary::-webkit-details-marker {
тут по-прежнему без изменений)

2021-07-02 09:18 UTC, akonuhov commented on 03-lection1/02-accordion/accordion.css
> +summary::-webkit-details-marker {
Исправил

2021-07-02 11:09 UTC, GSemikozov approved these changes

2021-07-02 11:09 UTC, merged