05 lection3
js-tasks-ru/htmlcss-20210610_alexandrkonuhov pull request #5
Opened 2021-06-27 10:51 UTC by akonuhov

2021-06-28 21:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-28 21:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-30 10:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-02 09:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-02 09:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-02 10:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-02 14:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-02 14:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-07 17:44 UTC, GSemikozov requested changes

2021-07-07 17:44 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    padding-top:120px;
это точно лишнее, если захотим где-то в проекте использовать тултип, то иконка с огромным паддингом точно вылезет боком)

2021-07-07 17:44 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform:translate(-50%, 39%);
второй параметр по оси Y - я бы все-таки привязал к свойству top или bottom - top: 0 | bottom: 100%. Если bottom: 100% то translate по оси Y вообще не нужен будет, если же   top: 0 - то translateY по высоте иконки.

2021-07-07 19:14 UTC, akonuhov commented on 05-lection3/01-tooltip/tooltip.css
> +    padding-top:120px;
Согласен. Убрал

2021-07-07 19:14 UTC, akonuhov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform:translate(-50%, 39%);
Исправил

2021-07-08 07:31 UTC, GSemikozov requested changes

2021-07-08 07:31 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%,225%);
здесь опять как-то странно используется translateY - 225%. 
поскольку стрелочка снизу - вот такой код будет правильным:
```
left:50%;
top:100%;
transform: translateX(-50%);
```
ссылка на живой пример в codepen - https://codepen.io/hermansemykozov/pen/abWZbLY

2021-07-08 07:31 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin-left:21px;
вместо марджинов лучше использовать паддинги (внутренние отступы) на родителе .tooltip__menu

2021-07-08 07:31 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal-container{
это вспомогательный стиль для внешней разметки, в блоку .modal не имеет отношения, поэтому его можно вынести в тег style хтмл страницы с решением дз

2021-07-08 07:31 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
у нас уже есть кнопки, поэтому здесь надо использовать уже готовый компонент - `button button_primary`. Если нужно добавить какой-то отступ - используем элемент модалки и микс `button button_primary modal__button` (.modal__button { margin-top: ... })

2021-07-08 07:31 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal{
раз есть класс блока, то тогда то что под id-шников выше - надо перенести сюда, а id удалить

2021-07-08 07:31 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__group{
тут и ниже - можно удалить, поскольку формы мы еще не верстали, их нет в этом ПР, + в фигме мы здесь добавляем лишь текст)
а если захочется добавить инпуты  - то это позже, когда элементы формы будут смерджены.

2021-07-08 07:31 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal{
по структуре БЭМ вышло совсем неправильно.
блок .modal - это то что сейчас под #modal.
то что сейчас .modal - это .modal__window.

2021-07-08 07:31 UTC, GSemikozov commented on components/page/page.css
> +        max-width: 1110px;
```
max-width: 1110px;
    width:100%;
    margin: 0 auto;
    ```
    это определено выше, не нужно дублировать)

2021-07-08 07:31 UTC, GSemikozov commented on components/preview/preview.css
> +    grid-template-columns: repeat(3, calc(33.3333% - 15px));
если мы используем gap - точно ли надо высчитывать ширину так `calc(33.3333% - 15px)`? лучше перепроверить

2021-07-08 07:31 UTC, GSemikozov commented on components/preview/preview.css
> +    margin: 1.5rem 0;
внешние отступы следую БЭМ мы не задаем - их можно задавать через родительский блок в который встраиваем текущий

2021-07-08 07:31 UTC, GSemikozov commented on components/preview/preview.css
> +.card{
это отдельный компонент, его надо вынести в components/card

2021-07-08 13:41 UTC, akonuhov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%,225%);
Исправил

2021-07-08 13:41 UTC, akonuhov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin-left:21px;
Поменял марджины на паддинги

2021-07-08 13:41 UTC, akonuhov commented on 05-lection3/02-modal/modal.css
> +.modal-container{
вынес в тег style

2021-07-08 13:41 UTC, akonuhov commented on 05-lection3/02-modal/modal.css
> +.button {
Подключил готовый button.css и использовал микс классов

2021-07-08 13:41 UTC, akonuhov commented on 05-lection3/02-modal/modal.css
> +.modal{
изменил классы

2021-07-08 13:41 UTC, akonuhov commented on 05-lection3/02-modal/modal.css
> +.modal__group{
поменял форму с инпутами на модалку с текстом.

2021-07-08 13:41 UTC, akonuhov commented on components/page/page.css
> +        max-width: 1110px;
удалил дублирующиеся правила

2021-07-08 13:41 UTC, akonuhov commented on components/preview/preview.css
> +    grid-template-columns: repeat(3, calc(33.3333% - 15px));
Исправил

2021-07-08 13:41 UTC, akonuhov commented on components/preview/preview.css
> +    margin: 1.5rem 0;
Вместо марджина добавил паддинг через родительский блок

2021-07-08 13:42 UTC, akonuhov commented on components/preview/preview.css
> +.card{
Готово

2021-07-08 13:47 UTC, GSemikozov requested changes

2021-07-08 13:47 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-close{
и все-таки id-шек в БЭМ мы избегаем, нужно поменять на класс

2021-07-08 13:57 UTC, akonuhov commented on 05-lection3/02-modal/modal.css
> +#modal-close{
Понял, исправил

2021-07-08 13:58 UTC, GSemikozov approved these changes

2021-07-08 13:59 UTC, merged