Бургер-меню, страницы компонентов и меню навигации
js-tasks-ru/htmlcss-20210610_alexandrkonuhov pull request #8
Opened 2021-07-15 15:31 UTC by akonuhov

2021-07-15 15:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-16 20:13 UTC, GSemikozov requested changes

2021-07-16 20:13 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-button{
если это триггер вызова в меню, тогда эта кнопка - часть хедера, надо описывать в хедере как его элемент

2021-07-16 20:13 UTC, GSemikozov commented on components/card/card.css
> +.card__columns{
а в каких карточках используются колонки?

2021-07-16 20:13 UTC, GSemikozov commented on components/modal/modal.css
> +
а где сам класс блока .modal?)

2021-07-17 09:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-17 09:18 UTC, akonuhov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-button{
Изменил на .header__burger-button и переместил описание в header.css

2021-07-17 09:18 UTC, akonuhov commented on components/card/card.css
> +.card__columns{
Использовал в карточке Custom form elements чтобы выровнять чекбоксы и радио кнопки ичтобы они не смешивались

2021-07-17 09:18 UTC, akonuhov commented on components/modal/modal.css
> +
Извиняюсь) Добавил

2021-07-17 13:00 UTC, GSemikozov commented on components/card/card.css
> +.card__columns{
это касается все-таки больше превью, поэтому я бы советовал больше конкретизировать класс модификатора - например, `.card_preview_columns`

2021-07-17 13:57 UTC, akonuhov commented on components/card/card.css
> +.card__columns{
Исправил

2021-07-17 13:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-17 14:24 UTC, GSemikozov approved these changes

2021-07-17 14:24 UTC, merged